version: '3.6'
services:
  iris:
    build: 
      context: ./iris
      dockerfile: Dockerfile
    restart: always
    container_name: iris
    ports: 
      - 51773
      - 52773:52773
      - 53773
    volumes:
      - ./iris/data:/durable 
    environment: 
      - ISC_DATA_DIRECTORY=/durable
    networks: 
      - production-network
networks: 
  production-network:
    driver: bridge
