version: '3.6'
services:
  iris:
    build: 
      context: ./iris
      dockerfile: Dockerfile
    restart: always
    container_name: iris
    ports: 
      - 51773
      - 52773:52773
      - 53773
    volumes:
      - ./iris:/irisdev/app
      - ./iris/data:/durable 
    environment: 
      - ISC_DATA_DIRECTORY=/durable
    networks: 
      - production-network
  react:
    build: 
      context: ./web
      dockerfile: Dockerfile
    restart: always
    container_name: react
    ports: 
      - 3000:3000
    depends_on: 
      - iris
    networks: 
      - production-network
    volumes:
      - ./web:/usr/app
networks: 
  production-network:
    driver: bridge
